In [1]:
import numpy as np 

In [2]:
list = [1, 2, 3]

In [3]:
type(list)

list

In [4]:
type(np.array(list))

numpy.ndarray

In [5]:
matrix = [[1, 2 ,3],[1 ,2 ,3], [1, 2, 3]]

In [6]:
type(matrix)

list

In [7]:
type(np.array(matrix))

numpy.ndarray

In [8]:
np.arange(0,11,1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.linspace(0,10,11) # we want 11 number in betwwen 0 and 10 so it automaticcaly counts the step between numbers

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
np.random.rand(1)

array([0.9110842])

In [16]:
np.random.rand(5,6) # Normal distribution in betwwen 0 and 1 

array([[0.58982164, 0.96127875, 0.62026655, 0.99865893, 0.25495058,
        0.33953419],
       [0.0559585 , 0.91760396, 0.60623367, 0.84309826, 0.86564417,
        0.89591017],
       [0.74540781, 0.79757737, 0.90060437, 0.71121492, 0.46709074,
        0.05773575],
       [0.88756522, 0.3167483 , 0.50373946, 0.47533616, 0.11461874,
        0.7307791 ],
       [0.04634769, 0.55123401, 0.27660631, 0.01675486, 0.34154979,
        0.54635402]])

In [17]:
list = np.arange(0,15)

In [18]:
print(list.min())
print(list.max())

0
14


In [19]:
list.argmax() # index of max 

14

In [20]:
list.argmin() # index of min

0

In [21]:
list.dtype  # dtype is not as type

dtype('int32')

In [22]:
arr = np.arange(0,25)

In [23]:
arr.shape

(25,)

In [24]:
arr1 = arr.reshape(5,5)

In [25]:
arr1.shape

(5, 5)

In [26]:
arr1.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [27]:
arr1.reshape(25,)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
import numpy as np
myarray = np.linspace(0,10,101)

In [29]:
myarray.shape

(101,)